### ISSUE TITLE
Can't use MoveGroup with use_controller_manager=false

### ISSUE THREAD

**Issue by JeremyZoss** [moveit/moveit_pr2#13]
Many robots don't need dynamic ControllerManager functions (dynamic load/unload, multi-controller support, etc.).  But the MoveIt Setup Assistant seems to suggest that a ControllerManager is required.  As a workaround, I am using the pr2_controller_manager with the use_controller_manager flag set to false.  Initially, this worked, but has recently broken.

To reproduce:
- take an existing MoveIt configuration (e.g. [irb_2400_moveit_config](http://code.google.com/p/swri-ros-pkg/source/browse/#svn/trunk/abb/irb_2400_moveit_config))
- modify launch file to set use_controller_manager = false
- launch planning environment for that config
- Plan a path
- Try to execute the path

What happens:
- the robot doesn't actually move
- the following sequence of messages is logged (with no delay between):
  1. move_group INFO:
     - `Received new trajectory execution service request...`
     - `move_group.cpp:MoveGroupServer::executeTrajectoryService:615`
  2. move_group WARNING:
     - `Cannot load controller without using the controller manager`
     - `pr2_moveit_controller_manager.cpp:Pr2MoveItControllerManager::loadController:453`
  3. move_group INFO:
     - `Execution completed: SUCCEEDED`
     - `move_group.cpp:MoveGroupServer::executeTrajectoryService:643`
- no move commands are actually sent on the move_group/goal or joint_trajectory_action/goal topics
- move_group/result shows a valid trajectory after the "plan" step, but no messages after the "execute" step

What should happen:
- the robot should move to follow the planned trajectory
- messages should be published on the goal topics
- the "Execution completed" message should not be posted until motion is completed

For reference, I'm using the ubuntu binary packages with the following versions:
- ros-groovy-moveit-ros-move-group v0.3.21 (20130305-1104)
- ros-groovy-pr2-moveit-plugins v0.3.7  (20130228-2321)

**Comment by isucan** [comment]
I can confirm the issues you mention. I believe they are now fixed (patches in moveit_ros and moveit_pr2). The error reporting was a forgotten status update on trajectory_execution_manager.
The setting of use_controller_manager=false actually works for you, but the controllers are reported as unloaded and inactive. So the trajectory execution attempts to load them, but there is no manager loaded, so it fails. This leads to the lack of commands to the controller itself.
The correct thing to do is to report the state of the controller used as active. I have changed the default moveit_pr2 controller plugin to be more optimistic, so it will assume unknown / unmanaged controllers are active, and it will send commands to them (if the controller is indeed missing, failure will happen a bit later). Let me know if this works (you would need to compile from source)

**Comment by JeremyZoss** [comment]
Thanks for the quick response & explanation.  I'll probably wait for the updates to work their way into the official binary release to verify the fix on my side, but I'll mark this closed for now.  I'll re-open if things don't work right in a week or two.

**Comment by JeremyZoss** [comment]
I checked today, and the fixes have been released into the public repository.  I was able to verify that this issue is fixed.  Thanks!

For reference, I'm now using the following versions:
- ros-groovy-moveit-ros-move-group v0.3.25 (20130319-1813)
- ros-groovy-pr2-moveit-plugins v0.3.9 (20130315-2034)
