### ISSUE TITLE
Moving the arm along a circular path

### ISSUE THREAD

**Issue by karyuv** [moveit/moveit_pr2#17]
Hi ,
I have been working with the Kinematics part of the pr2 tutorials(ros_api_tutorial).  I am able to move the arm to a desired x,y,z as per the tutorial. I need to set up a constraint where I can move the arm along a circular path. For example If I want it to move from x,y,z to x1,y1,z1 it should be done in a parabolic path than a straight line. Any thoughts?
Thanks,
Karthik

**Comment by isucan** [comment]
This is a question for the moveit-users mailing list. Please ask there and I will respond.
