### ISSUE TITLE
error in roslaunch pr2_moveit_config demo.launch

### ISSUE THREAD

**Issue by buckybots** [moveit/moveit_pr2#18]
On a freshly built : Groovy on Ubuntu 12.04.2
following the tutorial: Groovy/PR2/Rviz Plugin/Quick Start, after following the steps in:
Groovy/PR2/Setup Assistant/Quick Start.  The : Choose kdl_kinematics_plugin/KDLKinematicsPlugin as the kinematics solver.
step was followed as per the tutorial.  
running: roslaunch pr2_moveit_config demo.launch
errors for both the left and right arms : [ERROR] [1368942623.760077511]: The kinematics plugin (left_arm) failed to load. Error: According to the loaded plugin descriptions the class pr2_arm_kinematics/PR2ArmKinematicsPlugin with base class type kinematics::KinematicsBase does not exist. Declared types are  kdl_kinematics_plugin/KDLKinematicsPlugin

I think this causes in RVIZ the "Interact" to not function.

**Comment by sachinchitta** [comment]
Can you try "roscd pr2_moveit_plugins" and see if it gets to the right place. You don't seem to have moveit_pr2 installed. The pr2_moveit_config package (that we generated) uses the kinematics plugins from pr2_moveit_plugins while the instructions on the wiki use the KDL plugins.

**Comment by buckybots** [comment]
Thank you!

I am pretty sure the plugins had not been loaded, that is roscd could not
find the package.  I ran :  sudo apt-get install
ros-groovy-pr2-moveit-plugins
This loaded them, I then retried launching with :  roslaunch
pr2_moveit_config demo.launch
and I am now able to try the stuff out in the wiki.

Thanks again!!!

Eric
