### ISSUE TITLE
roslaunch pr2_moveit_config demo.launch  Issues

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_pr2#2]
When running 

> roslaunch pr2_moveit_config demo.launch

as suggested for beginners on the [installation page](http://moveit.ros.org/installation_source.html), the launch file Rviz is not loaded with a config file. This is hard for beginners.

Also, on my system I'm getting the following error output:
https://gist.github.com/4256083

**Comment by isucan** [comment]
How about we re-add your rviz config file? It seems the format has stablized now. Would you send a version that you like for that file?

**Comment by davetcoleman** [comment]
Done

**Comment by Ayushas2427** [comment]
@isucan , i am unable to get your solution. I am getting the same error. Could you help me in this regard with a more explanatory answer?

**Comment by davetcoleman** [comment]
This was fixed on this line:

https://github.com/ros-planning/moveit_pr2/blob/indigo-devel/pr2_moveit_config/launch/moveit_rviz.launch#L9
