### ISSUE TITLE
calculate path length

### ISSUE THREAD

**Issue by night89** [moveit/moveit_pr2#23]
Hi,
I have a lot of problems trying to do a benchmark for pr2, but I don't think I really need to build a benchmark!
I want to get only the path length, using 5 different algorithms on the same configuration of pr2 but the only way to get it seems to be the .log file resulting from a benchmark.
Do you know if there is a easier way to get it? For example publishing the resulting path length on /rosout like the computational time needed?

Thank you in advance

Ale

**Comment by isucan** [comment]
This is a question, please use the mailing list from now on.

There is nothing that publishes patch lengths. However, once you compute a solution, you can compute its length  easily with a for loop calling distance between states()
