### ISSUE TITLE
Benchmarking pr2

### ISSUE THREAD

**Issue by night89** [moveit/moveit_pr2#24]
Hi, 
I'm trying to benchmark the pr2 robot with some motion planning algorithms, but i get an error trying to run the db. I typed:

roslaunch pr2_moveit_config default_warehouse_db.launch

but i get the error:

OSError: [Errno 13] Permission denied: '/opt/ros/groovy/share/pr2_moveit_config/default_warehouse_mongo_db'
[mongo_wrapper_ros_ale_N51Vf_10534_1696917966-1] process has died [pid 10552, exit code 1, cmd /opt/ros/groovy/lib/warehouse_ros/mongo_wrapper_ros.py __name:=mongo_wrapper_ros_ale_N51Vf_10534_1696917966 __log:=/home/ale/.ros/log/01d548c4-14a0-11e3-9d5a-0022fa00f616/mongo_wrapper_ros_ale_N51Vf_10534_1696917966-1.log].
log file: /home/ale/.ros/log/01d548c4-14a0-11e3-9d5a-0022fa00f616/mongo_wrapper_ros_ale_N51Vf_10534_1696917966-1*.log

Anyone could help me?
Thank you

Ale

**Comment by marioprats** [comment]
Hi, the default_warehouse_db.launch uses a default database in the pr2_moveit_config package path, where a standard user does not have write permissions if it's installed from debians (under /opt). In that case you can specify a custom database path using warehouse.launch directly, e.g:

```
 roslaunch pr2_moveit_config warehouse.launch moveit_warehouse_database_path:=~/pr2_moveit_database
```

Hope that helps

**Comment by night89** [comment]
Of course.. that was the problem!
Thank you so much

Ale
