### ISSUE TITLE
parameter names in sensors_kinect.yaml

### ISSUE THREAD

**Issue by jiang0131** [moveit/moveit_pr2#26]
The parameter names shape_padding and shape_scale in moveit_pr2 / pr2_moveit_config / config / sensors_kinect.yaml should be changed to  padding_offset and padding_scale after the recent changes in perception/pointcloud_octomap_updater/src/pointcloud_octomap_updater.cpp

**Comment by isucan** [comment]
thank you for pointing this out!

**Comment by mikeferguson** [comment]
@isucan, is that in debs also now? We should probably drop an email to the user mailing list about this, since it could cause interesting issues if people didn't notice the commit.

**Comment by isucan** [comment]
good point! thanks! This is in the 0.5.8 debs for moveit_ros_*
