### ISSUE TITLE
Wrong launch file name in tutorial "Motion Planners/C++ API"

### ISSUE THREAD

**Issue by Wedontplay** [moveit/moveit_pr2#54]
Hi, looking the pr2 package i believe the correct launch file is  `motion_planning_api_tutorial.launch` instead of  `motion_planning_interface_tutorial.launch` as reported on the tutorial.

link to the tutorial:
http://docs.ros.org/api/pr2_moveit_tutorials/html/planning/src/doc/motion_planning_api_tutorial.html

**Comment by hersh** [comment]
fixed here: https://github.com/ros-planning/moveit_pr2/commit/d38847c36643c38a164eb143245205c1da02b4f5
