### ISSUE TITLE
Release to Indigo

### ISSUE THREAD

**Issue by davetcoleman** [moveit/moveit_pr2#55]
I'm not sure what is block this from being released, but pr2_moveit_tutorials (where the documentation is generated) is being held back because of it

**Comment by davetcoleman** [comment]
I believe this can be released now? 
https://github.com/PR2/pr2_controllers/issues/373

**Comment by mikeferguson** [comment]
Yep, I plan to do a round of several releases tonight.

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/6858
