### ISSUE TITLE
Adding/Removing Objects, Dual-arm pose goals missing in move_group_interface_tutorial.py

### ISSUE THREAD

**Issue by rahul003** [moveit/moveit_pr2#58]
Tutorials for Adding/Removing Objects, and Dual-arm pose goals are incomplete/missing in moveit_pr2/pr2_moveit_tutorials/planning/scripts/move_group_interface_tutorial.py .

The same tasks are shown in the cpp tutorial

**Comment by kirantokala** [comment]
For me also, Same problem.

Is it possible to provide the Sample code for that.

**Comment by davetcoleman** [comment]
Are you aware the PR2 tutorials have been moved to https://github.com/ros-planning/moveit_tutorials/?

**Comment by kirantokala** [comment]
Sorry. I am not aware of this.

But in above link also, I didn't find move_group_interface_tutorial.py file

**Comment by davetcoleman** [comment]
Try https://github.com/ros-planning/moveit_tutorials/blob/kinetic-devel/doc/pr2_tutorials/planning/scripts/move_group_python_interface_tutorial.py

**Comment by kirantokala** [comment]
Yes. But in that I am unable to find code for this concept

**Comment by kirantokala** [comment]
## Adding/Removing Objects and Attaching/Detaching Objects
