### ISSUE TITLE
planning_context.launch should not always load robot_description

### ISSUE THREAD

**Issue by aleeper** [moveit/moveit_pr2#7]
planning_context.launch always loads the robot description, which is not necessary on a real robot and increases "launch" time quite a bit.
There should be a launch arg that makes this optional. 
move_group.launch will also need that launch arg, since it calls planning_context.launch

Is this a general issue with the setup_assistant?

**Comment by isucan** [comment]
This is how the setup assistant generates the files yes. I think move_group should not call planning_context.launch and planning_context should have an argument, yes. One for URDF (default off) and one for SRDF (default on)

**Comment by aleeper** [comment]
Should I make this a ticket against moveit_setup_assistant then? (Do we manually edit any of the files in moveit_pr2, or does everything come from re-running setup_assistant?)

**Comment by isucan** [comment]
If it is simple, i edit moveit_pr2 files; but we also need to fix the setup assistant. We can leave the bug here for now.

**Comment by davetcoleman** [comment]
I'm not sure when but this has already been solved. In planning_context.launch by default it does not load the robot description:

```
<arg name="load_robot_description" default="false"/>
```
