### ISSUE TITLE
Release into Jade

### ISSUE THREAD

**Issue by 130s** [moveit/moveit_pr2#71]
Required by https://github.com/ros-planning/moveit_metapackages/issues/6

Currently blocked at https://github.com/PR2/pr2_kinematics/issues/6, which is also confirmed as follows:

```
$ wget https://raw.githubusercontent.com/ros/rosdistro/master/scripts/check_blocking_repos.py && chmod 755 check_blocking_repos.py
$ python ./check_blocking_repos.py --rosdistro jade --repositories moveit_pr2 --depth 1
The following repos cannot be released because of unreleased dependencies:
        moveit_pr2:
                pr2_kinematics
```

**Comment by ngupta1024** [comment]
is this repo suppose to work with indigo?

**Comment by 130s** [comment]
Even binary is available for Indigo http://repositories.ros.org/status_page/ros_indigo_default.html?q=moveit_pr2 so yes.

**Comment by 130s** [comment]
Jade is approaching EOL in a few months. I suggest to drop this package support, and rather want to focus on Kinetic release. Feel free to reopen if there's any objection.
