### ISSUE TITLE
moveit_setup_assistant cannot load pr2.urdf.xacro 

### ISSUE THREAD

**Issue by Shawnnn** [moveit/moveit_pr2#83]
Here is a detailed information linking to ROS answer.
http://answers.ros.org/question/247687/moveit_setup_assistant-cannot-load-pr2urdfxacro/?answer=247695
Thanks for your help!

**Comment by davetcoleman** [comment]
This is likely an issue with Rviz, your graphics drivers, and your use of a VM.

**Comment by 130s** [comment]
Question at the link seems to have been resolved. If there's any suggestion to the software on this repo please provide more info (preferably a pull request).
