### ISSUE TITLE
move pr2 base with moveit

### ISSUE THREAD

**Issue by zychaoqun** [moveit/moveit_pr2#84]
Hello ,Is it possible to move the base of Pr2 using moveit? It seems that we can only move the arm using moveit. I would like to test my planning algorithms with mobile ground robot.

**Comment by davetcoleman** [comment]
You should be able to plan for a "virtual planar joint" that represents the base of the PR2, but only for holonomic systems (no diff drive, etc)

**Comment by v4hn** [comment]
Closing, because at least for now it is not within the scope of this repository to move the base via moveit.
Overall, this is not a well-tested feature in MoveIt.

If you can implement support for it in moveit_pr2, feel free to add a pull-request.
