### ISSUE TITLE
Release into Kinetic?

### ISSUE THREAD

**Issue by 130s** [moveit/moveit_pr2#86]
We dropped Jade release https://github.com/ros-planning/moveit_pr2/issues/71
`pr2_moveit_config` is depended by https://github.com/ros-planning/moveit_tutorials/issues/65
Is there a plan to make a release into K? If so what has to be done?

I can take care of bloom stuff if desired.

**Comment by v4hn** [comment]
> Is there a plan to make a release into K?

Yes.

> If so what has to be done?

Basically the same as for the jade issue. Just more.
Clearpath currently has their hands on the PR2 repositories but they do not support them officially anymore.
This will take some more time, but I'm confident we will see releases of the required ROS packages in kinetic.
It's on my ToDo list to deal with this.

**Comment by k-okada** [comment]
pr2 on kinetic is now released, so please release mvoeit_pr2 into kinetic.

**Comment by 130s** [comment]
I don't have an extra gear for this any more. I appreciate if either @v4hn or @k-okada has an access rights and take this over.

**Comment by v4hn** [comment]
It's on my todo list, but I'm not sure when I will get around to do that either.
Also I just noticed I do not yet have access to ros-gbp/moveit_pr2-release .

**Comment by bmagyar** [comment]
If I'm given access to the required repos I can also help with releases from time to time.

**Comment by 130s** [comment]
@mikaelarguedas Sorry to pull you in, but assuming you have admin access can you add write access to @bmagyar @v4hn? Thanks in advance.

Maintainer field in package.xml is outofdate so @bmagyar @v4hn please consider adding yourself/ves there as well.

**Comment by mikaelarguedas** [comment]
I don't have access to ros-planning ATM, maybe @v4hn or @davetcoleman have enough permissions to grant access to the source repository to the new maintainers? Otherwise I can look into getting the required permissions to add them.

I can give write access to the release repository. My understanding is that @bmagyar and @v4hn  will be added as contributors to the `moveit_pr2-release` repository and not added globally to the `ros-planning` team. Is that correct ?

**Comment by 130s** [comment]
@mikaelarguedas I think that's right. Thanks!

**Comment by bmagyar** [comment]
Let us know once we have the permission and I'll go ahead with running some tests.

**Comment by mikaelarguedas** [comment]
@bmagyar @v4hn added as collaborators to the https://github.com/ros-gbp/moveit_pr2-release repo

**Comment by bmagyar** [comment]
I started testing some builds. It seems there are a few changes on rosdep keys, messages and some C++11-related ones. I'll try to get to the end of it tomorrow and push a release to Kinetic.

Any plans for Melodic?

**Comment by v4hn** [comment]
Please file pull-requests for any change you need to make in this repository before you release.

**Comment by bmagyar** [comment]
Of course. All will be going against the `kinetic-devel` branch.

**Comment by bmagyar** [comment]
WIP #96

**Comment by bmagyar** [comment]
As an extra I also threw in https://github.com/PR2/pr2_common/pull/269, the warnings were annoying :)

**Comment by davefeilseifer** [comment]
I've taken over maintainership of the pr2 packages and released almost all pr2 packages in kinetic. It might be worth some effort to try releasing the full suite of packages in kinetic again.

**Comment by bmagyar** [comment]
This ticket should have been closed after I released it the last time but I can push a new one with the urdf compatibility changes, hold tight!

**Comment by bmagyar** [comment]
I ran tests locally as the CI seems to be super slow today: https://travis-ci.org/ros-planning/moveit_pr2/jobs/513757640

PR:
https://github.com/ros/rosdistro/pull/20777

If you are happy, feel free to close this issue.

**Comment by davefeilseifer** [comment]
I didn't open the issue, so I cannot close it
