### ISSUE TITLE
process crashed after using new planner and state space

### ISSUE THREAD

**Issue by ruinianxu** [moveit/moveit_pr2#90]
I am adding new planner and state space to source ompl and trying to do simulation on pr2 robot. About my modification to moveit and ompl, for ompl, I just directly added header and cpp files of new planner and state space into ompl source code and built it up. For moveit, I changed planning_context_manager.cpp file in ompl to include my planner and state space for pr2. And in planning_request_adapter.cpp file, I let my planner to use state space I wrote. The above is basically what I did to introduce new planner. Actually I am not sure whether I am missing some steps somewhere. 
Then I compiled all codes out but somethings wrong happened when simulation. Every other planner works find but for my planner, process will always crash. I found when I choose other planner to plan a path for robot, it will directly start planning but for my planner, it seems try to reload pr2 robot model and eventually it shows up "SEVERE WARNING!!! Attempting to unload library while objects created by this loader exists in the heap! You should delete your objects before attempting to unload the library or destroying the ClassLoader. The library will NOT be unloaded" and then process will crash. I am not sure whether the about is the reason why my process crashes. I am not familiar with the order of moveit solving motion planning problem. Hence I don't know where I should start to debug. Really appreciate it if someone can give suggestion.
Here is the output when my process crashes:
`[ INFO] [1497899368.117001606]: Loading robot model 'pr2'...
[ WARN] [1497899368.135801603]: The root link base_footprint has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ WARN] [1497899368.189987252]: The root link base_footprint has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ WARN] [1497899368.219836276]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.219915319]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.219936382]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.219959715]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220056698]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220078636]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220104077]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220122574]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220229304]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220253929]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220272559]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220290697]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220347641]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220365842]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220383068]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220400090]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220487693]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220508043]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220526174]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220544129]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220690069]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220712522]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220730112]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220748265]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220821778]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220841200]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220859438]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220876878]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220973242]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.220994061]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221012750]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221031930]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221166296]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221192153]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221211757]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221231545]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221311855]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221330873]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221348801]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221367709]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221452893]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221476088]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221499876]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221517753]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221582881]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221605406]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221628522]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221646322]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221710233]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221733293]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221756212]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221773677]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221827455]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221850652]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.221976619]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222010183]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222073109]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222097250]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222119951]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222142440]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222200529]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222223990]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222250508]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222268687]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222379584]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222403924]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222427583]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222445119]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222462890]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222486469]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222525930]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222549417]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222569023]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222590655]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222608157]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222631480]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222648847]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222672151]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222689523]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222707344]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222724160]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222741308]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222758496]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222776202]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222794739]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222818803]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222836339]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222853900]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222876995]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222898598]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222915403]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222933089]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222950007]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222967031]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.222985362]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223003853]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223028585]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223050510]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223068105]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223085363]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223103733]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223129279]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223147136]: Link 'head_mount_kinect_ir_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223164337]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223185944]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223208076]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223225585]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223248047]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223270130]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223287624]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223309620]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223331612]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223349440]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223373657]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223391050]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223412880]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223435014]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223452407]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223469681]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223488873]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223521971]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223539798]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223560626]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223583414]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223600835]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223621694]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223644066]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223661793]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223684696]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223706793]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223724451]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223749500]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223767368]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223786335]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223806785]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223824391]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223841764]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223859033]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223877339]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223909874]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223933287]: Link 'head_mount_kinect_rgb_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223951086]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223968876]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.223988272]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224014315]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224031735]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224049305]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224073253]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224091132]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224111755]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224130730]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224153557]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224175796]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224192660]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224211260]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224230139]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224253683]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224276225]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224293213]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224310931]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224330727]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224353489]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224370658]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224388649]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224409516]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224426747]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224444145]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224461193]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224478938]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224495583]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224512688]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224529598]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224546427]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224563396]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224580355]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224597215]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224681423]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224704280]: Link 'head_mount_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224734286]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224754503]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224771923]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224789890]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224807038]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224824496]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224841784]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224867292]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224889745]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224907527]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224924663]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224941778]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224958613]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224975940]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.224992917]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225010867]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225027642]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225044665]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225061291]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225078185]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225094970]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225112503]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225129291]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225146410]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225163492]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225180724]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225197702]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225214942]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225233387]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225251973]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225270452]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225288597]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.225307092]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.228985279]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.229095130]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ WARN] [1497899368.229186676]: Link 'head_mount_prosilica_link' is not known to URDF. Cannot disable collisons.
[ INFO] [1497899368.231695776]: Loading robot model 'pr2'...
[ WARN] [1497899368.251364029]: The root link base_footprint has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1497899368.257786618]: Model frame: /odom_combined
[ WARN] [1497899368.257959461]: SEVERE WARNING!!! Attempting to unload library while objects created by this loader exist in the heap! You should delete your objects before attempting to unload the library or destroying the ClassLoader. The library will NOT be unloaded.
[ WARN] [1497899368.257984387]: SEVERE WARNING!!! Attempting to unload library while objects created by this loader exist in the heap! You should delete your objects before attempting to unload the library or destroying the ClassLoader. The library will NOT be unloaded.
[move_group-5] process has died [pid 17194, exit code -11, cmd /home/ruinianxu/ws_moveit/devel/lib/moveit_ros_move_group/move_group --debug __name:=move_group __log:=/home/ruinianxu/.ros/log/39e934c0-5522-11e7-b786-1c6f6540c1be/move_group-5.log].
log file: /home/ruinianxu/.ros/log/39e934c0-5522-11e7-b
`

**Comment by v4hn** [comment]
This is not related to `moveit_pr2` but either to ompl or to moveit directly.
So sorry, but I'll close this here.

At first glance this looks like you use ROS related constructs that should not be used within the planner anymore. But I'm currently not familiar enough with the planning-internal classes to give proper pointers here.
