### ISSUE TITLE
how to know the whole flow of motion planning for pr2 roboot

### ISSUE THREAD

**Issue by ruinianxu** [moveit/moveit_pr2#91]
I introduced new planner and state space but there is some errors now. After code exit callPlannerInterfaceSolve function in planner_request_adapter file, process just die. I don't know the whole flow of doing motion planning for pr2 robot. Hence, I don't know after code exiting callPlannerInterfaceSolve function, it will come into which file or function. Can anybody tell me the whole flow of doing motion planning in demo.launch of pr2 robot? Or which file it will come into after it exiting callPlannerInterfaceSolve function.

**Comment by bmagyar** [comment]
We are using issues to track software-related issues of the software.
Please raise your question on [ROS answers](https://answers.ros.org/questions/)
