### ISSUE TITLE
The kinematics plugin (right_arm) failed to load.

### ISSUE THREAD

**Issue by maxgittelman** [moveit/moveit_pr2#93]
Hello,

I am working though the [MoveIt! RViz Plugin Tutorial](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/ros_visualization/visualization_tutorial.html) and noticed an error in the launching of the demo file.

When executing: `roslaunch pr2_moveit_config demo.launch`, I noticed the following Error:

![right_arm_kinematics](https://user-images.githubusercontent.com/30596770/33456455-7eccb192-d5ed-11e7-8c23-844362f30ef3.png)

Why should I be or not be worried by this?

**Comment by davetcoleman** [comment]
Is this on Kinetic? The PR2 has poor support on kinetic

**Comment by maxgittelman** [comment]
Yes, this is on Kinetic

**Comment by rhaschke** [comment]
Try to use KDL IK plugin instead.

**Comment by davetcoleman** [comment]
I believe @rhaschke provided a good solution to this
